#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: R Survey Analysis Extra Tools
#+date: <2021-02-05 Fri>
#+author: Daniel Ballesteros-Chavez, Jorge Becerril-Cejudo and Miguel López-Cruz
#+email: 
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 26.1 (Org mode 9.3.6)

*  Introduction
Some code using R and the survey package.

We will discuss how to use the files:
+ survey_extra_tools.R
+ gentab.sh

The core of the functions defined in the first file is the [[https://cran.r-project.org/web/packages/survey/][survey package]], whereas the second file is a Bash script for UNIX-like systems.

In this document we will describe the tools we have been developing in order to produce the analysis of surveys. 
One is usually interested in obtaining totals, means and ratio estimates from a data set that contains results of a survey and which includes
a variable with the weights corresponding to the sampling design.

In our examples we consider *Crime Victimisation Surveys* from different statistical offices, usually with a multi-stage sampling design behind them.


* Sampling design

We assume you have a data frame stored in the object _df_, and that you would like to run the analysis of the variable "VAR". The data set should also contains 
the information related to the sample design, namely the strata, and the Primarily Sampling Units (PSU) as well as the corresponding weights:

+ Definition of the weights :: =df$W  <- df$Variable.Weights=
+ Definition of  PSU :: =df$PSU  <- df$Variable.PSU=
+ Definition of Strata :: =df$STR  <-  df$Variable.Strata=
+ Definition of the LEVELS :: =df$LEVELS  <-  df$Variable.Levels=

The *varnames* is a character vector including the name or names of the variables to be analysed. *codes* is the values (or answers) given to the corresponding question in the survey, and usually takes a numerical value.

=varnames  <- c("VAR")=

=codes  <- c(1,2,9)=

The *denovarnames* variable is a character vector containing the name of the variable to be used as denominator for the variable to be analysed. It is the denominator
in a ratio estimate. *denocodes* are the union of according to the set of values given. For example if we set:

=denovarnames  <- c("VAR")=

=denocodes  <- c(1,2,9)=

then the denominator value is the total estimate of =("VAR" = = 1 OR "VAR" = = 2 OR "VAR" = = 9)=.


+ Definition of the survey design :: =mydesign <- svydesign(id=~PSU,strata=~STR,data=df,weights=~W)=
 

* Survey analysis examples

** ENVIPE 2019. INEGI, Mexico. Perception of feeling safe in the State

The Statistical Office in Mexico has an open-data policy, en you can download the data set of the Crime Victimisation Survey form

https://www.inegi.org.mx/contenidos/programas/envipe/2019/Microdatos/bd_envipe2019_dbf.zip

The zip file contains six .dbf files. We will be interested in answers from the main questionnaire =TPer_Vic1.dbf=, where among other things, includes the 
variable =AP4_3_3=, that corresponds to the question

*4.3.3* How do you feel in the STATE OF THE REPUBLIC that you live in, in terms of crime and safety?. 1. SAFE , 2. NOT SAFE, 9. REFUSE TO ANSWER.

Note that a fundamental requirement is a previous exploration of the data set and data cleansing, as well as be aware of the documentation for the project.
In the Following we will obtain the totals and ratio estimates for the perception of feeling safe using the function =A.estimator=.

#+begin_src R

## Usage Example:

library(foreign) ## Needed to read dbf files
library(survey) ## Main tools for survey analysis

source("./survey_extra_tools.R") ## Our implementation

## Reading the data set and preparing for analysis
df  <- read.dbf("./TPer_Vic1.dbf")
df$Variable.Weights  <- as.numeric(as.character(df$FAC_ELE))

## Definition of the weights

df$W  <- df$Variable.Weights

## Definition of  PSU
df$PSU  <- df$UPM_DIS

## Definitinon of Strata
df$STR  <-  df$EST_DIS

## Definition of the LEVELS
df$LEVELS  <-  df$NOM_ENT

## Variable and codes to be analysed
varnames  <- c("AP4_3_3")
codes  <- c(1,2,9)


## Denominator: From "AP4_3_3" the ones that answer 1 or 2 or 9:

denovarnames  <- c("AP4_3_3")
denocodes  <- c(1,2,9)


## Definition of survey design
mydesign <- svydesign(id=~PSU,strata=~STR,data=df,weights=~W)


## Definition of Output path to filename:

filename  <-  "./File_AP4_3_3_OUT"


## A.estimator
A.estimator() ## Running with default values
#+end_src

*** Printing results

The output of =A.estimator= is a .csv file with the following column names:

+ =(none)= : the first column has no name, and it has row numbers.
+ =NAME= : Contains the variable name and the corresponding code, in the previous example it has  =variable.AP4_3_3.01=, =variable.AP4_3_3.02= and =variable.AP4_3_3.09=.
+ =LEVELS.denominator=: The variable specifying the subsets of the =denominator= variable, in this case the states (including the total).
+ =VALUE.denominator=: Total estimate for the =denominator= variable.
+ =SE.denominator=: The Standard Error for the total of the =denominator= variable.
+ =CV.denominator=: The Coefficient of Variance for the total of the =denominator= variable.
+ =INF.95.denominator=: The lower bound of the confidence interval for the total of the =denominator= variable.
+ =SUP.95.denominator=: The upper bound of the confidence interval for the total of the =denominator= variable.
+ =LEVELS.total=: The variable specifying the subsets of the =AP4_3_3= variable, in this case the states (including the total).
+ =VALUE.total=: Total estimate for the =AP4_3_3= variable.
+ =SE.total=: The Standard Error for the total of the =AP4_3_3= variable.
+ =CV.total=: The Coefficient of Variance for the total of the =AP4_3_3= variable.
+ =INF.95.total=: The lower bound of the confidence interval for the total of the =AP4_3_3= variable.
+ =SUP.95.total=: The upper bound of the confidence interval for the total of the =AP4_3_3= variable.
+ =LEVELS.mean=: The variable specifying the subsets of the =AP4_3_3= variable, in this case the states (including the total).
+ =VALUE.mean=: Ratio estimate for the =AP4_3_3= variable.
+ =SE.mean=: The Standard Error for the Ratio of the =AP4_3_3= variable.
+ =CV.mean=: The Coefficient of Variance for the Ratio of the =AP4_3_3= variable.
+ =INF.95.mean=: The lower bound of the confidence interval for the Ratio of the =AP4_3_3= variable.
+ =SUP.95.mean=: The upper bound of the confidence interval for the Ratio of the =AP4_3_3= variable.


** Final User's Tables

Now that we have the CSV file with all the interesting estimates, we proceed to run *gentab*. This is a very small script that uses
awk and perl to obtain a *.xls* file with 3 scale background format. Usually we want to high-light the estimates with coefficient of
variations (c.v.'s) according to a certain range of values. 

#+begin_src sh 
./gentab.sh File_AP4_3_3_OUT2021-02-09\ 13\:59\:47.csv
#+end_src

The output is the file [[https://github.com/ennaniux/R_Surveys/raw/master/myExcel.xls][myExcel.xls]]
