#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: R tools for Survey Analysis
#+date: <2021-02-05 Fri>
#+author: Daniel Ballesteros-Chavez, Jorge Becerril-Cejudo and Miguel López-Cruz
#+email: 
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 26.1 (Org mode 9.3.6)
#+header:  Daniel Ballesteros-Chavez, Jorge Becerril-Cejudo and Miguel López-Cruz

*  Introduction
Some code using R and the survey package.

The core of the functions defined here is the [[https://cran.r-project.org/web/packages/survey/][survey package]].

In this document we will describe the tools we have been developing in order to produce the analysis of surveys. 
One is usually interested in obtaining totals, means and ratio estimates from a data set that contains results of a survey and which includes
a variable with the weights corresponding to the sampling design.

In our examples we consider Crime Victimisation Surveys from different statistical offices, usually with a multi-stage sampling design behind them.


* Sampling design

We assume you have a data frame stored in the object _df_, and that you would like to run the analysis of the variable "VAR". The data set should also contains 
the information related to the sample design, namely the strata, and the Primarily Sampling Units (PSU) as well as the corresponding weights:

+ Definition of the weights :: =df$W  <- df$Variable.Weights=
+ Definition of  PSU :: =df$PSU  <- df$Variable.PSU=
+ Definition of Strata :: =df$STR  <-  df$Variable.Strata=
+ Definition of the LEVELS :: =df$LEVELS  <-  df$Variable.Levels=

The *varnames* is a character vector including the name or names of the variables to be analysed. *codes* is the values (or answers) given to the corresponding question in the survey, and usually takes a numerial value.

=varnames  <- c("VAR")=

=codes  <- c(1,2,9)=

The *denovarnames* variable is a character vector containing the name of the variable to be used as denominator for the variable to be analised. It is the denominator
in a ratio estimate. *denocodes* are the union of according to the set of values given. For example if we set:

=denovarnames  <- c("VAR")=

=denocodes  <- c(1,2,9)=

then the denominator value is the total estimate of =("VAR" = = 1 OR "VAR" = = 2 OR "VAR" = = 9)=.


+ Definition of the sruvey design :: =mydesign <- svydesign(id=~PSU,strata=~STR,data=df,weights=~W)=
 

* Survey analysis examples


* Printing results
